-- MySQL Script generated by MySQL Workbench
-- vie 11 may 2018 13:13:15 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema consultorio
-- -----------------------------------------------------
-- Esquema de base de datos para aplicacion Ophiuchus Control

-- -----------------------------------------------------
-- Schema consultorio
--
-- Esquema de base de datos para aplicacion Ophiuchus Control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OphiuchusControlDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `OphiuchusControlDB` ;

-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Medico` (
  `CedulaProfesional` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApellidoParteno` VARCHAR(30) NOT NULL,
  `ApellidoMaterno` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Email` VARCHAR(35) NULL,
  `Password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`CedulaProfesional`),
  UNIQUE INDEX `CedulaProfesional_UNIQUE` (`CedulaProfesional` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Especialidad` (
  `Nombre` VARCHAR(75) NOT NULL,
  `CedulaProfesional` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`CedulaProfesional`, `Nombre`),
  INDEX `fk_Especialidad_Medico_idx` (`CedulaProfesional` ASC),
  CONSTRAINT `fk_Especialidad_Medico`
    FOREIGN KEY (`CedulaProfesional`)
    REFERENCES `OphiuchusControlDB`.`Medico` (`CedulaProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Paciente` (
  `Curp` VARCHAR(18) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApellidoParteno` VARCHAR(30) NOT NULL,
  `ApellidoMaterno` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Email` VARCHAR(35) NULL,
  PRIMARY KEY (`Curp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Empleado` (
  `idEmpleado` VARCHAR(25) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApellidoPaterno` VARCHAR(30) NOT NULL,
  `ApellidoMaterno` VARCHAR(30) NOT NULL,
  `Puesto` VARCHAR(40) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Cita` (
  `FechaHora` DATETIME NOT NULL,
  `PacienteCurp` VARCHAR(18) NOT NULL,
  `CedulaProfesional` VARCHAR(8) NOT NULL,
  `Costo` FLOAT NULL,
  `idEmpleado` VARCHAR(25) NULL,
  PRIMARY KEY (`FechaHora`, `PacienteCurp`, `CedulaProfesional`),
  INDEX `fk_Cita_Medico1_idx` (`CedulaProfesional` ASC),
  INDEX `fk_Cita_Empleado1_idx` (`idEmpleado` ASC),
  INDEX `fk_Cita_Paciente1_idx` (`PacienteCurp` ASC),
  CONSTRAINT `fk_Cita_Medico1`
    FOREIGN KEY (`CedulaProfesional`)
    REFERENCES `OphiuchusControlDB`.`Medico` (`CedulaProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `OphiuchusControlDB`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Paciente1`
    FOREIGN KEY (`PacienteCurp`)
    REFERENCES `OphiuchusControlDB`.`Paciente` (`Curp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`HistorialClinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`HistorialClinico` (
  `CedulaProfesional` VARCHAR(8) NOT NULL,
  `PacienteCurp` VARCHAR(18) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `RutaArchivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CedulaProfesional`, `PacienteCurp`, `Nombre`),
  INDEX `fk_HistorialClinico_Paciente1_idx` (`PacienteCurp` ASC),
  CONSTRAINT `fk_table1_Medico1`
    FOREIGN KEY (`CedulaProfesional`)
    REFERENCES `OphiuchusControlDB`.`Medico` (`CedulaProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HistorialClinico_Paciente1`
    FOREIGN KEY (`PacienteCurp`)
    REFERENCES `OphiuchusControlDB`.`Paciente` (`Curp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OphiuchusControlDB`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`Permiso` (
  `CedulaProfesional` VARCHAR(8) NOT NULL,
  `idEmpleado` VARCHAR(25) NOT NULL,
  `Permiso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`CedulaProfesional`, `idEmpleado`),
  INDEX `fk_Medico_has_Empleado_Empleado1_idx` (`idEmpleado` ASC),
  INDEX `fk_Medico_has_Empleado_Medico1_idx` (`CedulaProfesional` ASC),
  CONSTRAINT `fk_Medico_has_Empleado_Medico1`
    FOREIGN KEY (`CedulaProfesional`)
    REFERENCES `OphiuchusControlDB`.`Medico` (`CedulaProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Empleado_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `OphiuchusControlDB`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `OphiuchusControlDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `OphiuchusControlDB`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OphiuchusControlDB`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `OphiuchusControlDB`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OphiuchusControlDB`.`view1`;
USE `OphiuchusControlDB`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
